#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header.

host_name="$HOSTNAME"

sudo sed -i "/Default server configuration/a add_header X-Served-By '${host_name}';" /etc/nginx/sites-available/default
sudo service nginx restart
