#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get purge haproxy > /dev/null 2>&1
sudo rm -rf /etc/haproxy /var/lib/haproxy /etc/default/haproxy > /dev/null 2>&1
sudo apt-get update > /dev/null 2>&1
sudo apt-get install haproxy -y > /dev/null 2>&1
sudo cp -a /etc/haproxy/haproxy.cfg{,.old}
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null 2>&1
sudo bash -c 'cat <<EOT >> /etc/haproxy/haproxy.cfg

frontend my_http_in
        bind    *:80
        mode    http
        default_backend my_http_backend

backend my_http_backend
        mode    http
        balance roundrobin
        server  88037-web-01 3.84.238.227:80 check
        server  88037-web-02 100.25.151.112:80 check
EOT'
sudo service haproxy restart
