#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y
sudo apt-get install haproxy=2.6.\* -y
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.old_copy}
sudo sed -i "$ a\
frontend http-in \\
	mode http \\
	bind *:80 \\
	default_backend $HOSTNAME \\
backend $HOSTNAME \\
	balance roundrobin \\
	server web-01 3.84.238.227:80 check \\
	server web-02 100.25.151.112:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
