#!/usr/bin/env bash
# A bash script that generates a MySQL dump and creates a compressed archive out of it.

# If argument is passed, the script can run
if [ -n "$1" ]; then
	# Store the MySQL root password in a variable
	passwd="$1"
	# Store the current date
	date=$(date +"%d-%m-%Y")
	# MySQL dump must be name backup.sql
	backup="backup.sql"
	# The above dump file has to be compresssed to a tar.gz archive
	archive="$date.tar.gz"
	# Create the MySQL dump
	mysqldump -u root -p"$passwd" --all-databases > "$backup"
	# Create the archive file
	tar -cvzf "$archive" "$backup"
fi
