#!/usr/bin/env bash
# A Bash script that displays Best School 10 times, but Hi for the 9th iteration

num=1

while [ $num -le 10 ]
do
	if [ $num == 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	num=$(( num+1 ))
done
