#!/usr/bin/env bash
# A bash script that configures an Ubuntu server with the requirements:
#	localhost resolves to 127.0.0.2
#	facebook.com resolves to 8.8.8.8

# Create a backup of the existing hostfiles
cp /etc/hosts /etc/hosts.old
echo "127.0.0.2	localhost" > /etc/hosts.new
echo "8.8.8.8	facebook.com" >> /etc/hosts.new
cp /etc/hosts.new /etc/hosts
