#!/usr/bin/env bash
# Run Nginx as nginx user, and nginx must be listening on all active IPs on port 8080

# Find user and all after it and replace with user nginx
sudo sed -i 's/^user.*/user nginx;/g' /etc/nginx/nginx.conf
# Find http and append the server block
sudo sed -i "/^http {/a\\
	server {\\
		listen 8080 default_server;\\
		listen [::]:8080 default_server;\\
	}" /etc/nginx/nginx.conf
# Restart the nginx service
sudo service nginx restart
